export const TOOLKIT_INTERNAL_LOGGER = Symbol('TOOLKIT_INTERNAL_LOGGER');
export const TOOLKIT_INTERNAL_UI_PRINTER = Symbol('TOOLKIT_INTERNAL_UI_PRINTER');
export const TOOLKIT_INTERNAL_COMMAND_REGISTRY = Symbol('TOOLKIT_INTERNAL_COMMAND_REGISTRY');
export const TOOLKIT_INTERNAL_CONFIG = Symbol('TOOLKIT_INTERNAL_CONFIG');
